// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnLtyZQg3mF9YbH0dFqQvvruFVx_nnSz4',
    appId: '1:106014869880:web:9cd19ca3b04d50ca5d208d',
    messagingSenderId: '106014869880',
    projectId: 'eddy-c0aa1',
    authDomain: 'eddy-c0aa1.firebaseapp.com',
    storageBucket: 'eddy-c0aa1.firebasestorage.app',
    measurementId: 'G-K2FVTZGCJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRgCE48wrhmEfHR3teg88iyTRldM_zH74',
    appId: '1:106014869880:android:736398016f392ab95d208d',
    messagingSenderId: '106014869880',
    projectId: 'eddy-c0aa1',
    storageBucket: 'eddy-c0aa1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF5D4OTEW5UQcyTKLEraVcO1g3UfIOoCA',
    appId: '1:106014869880:ios:eeea36f92166a2ef5d208d',
    messagingSenderId: '106014869880',
    projectId: 'eddy-c0aa1',
    storageBucket: 'eddy-c0aa1.firebasestorage.app',
    iosBundleId: 'com.example.appTienganh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF5D4OTEW5UQcyTKLEraVcO1g3UfIOoCA',
    appId: '1:106014869880:ios:eeea36f92166a2ef5d208d',
    messagingSenderId: '106014869880',
    projectId: 'eddy-c0aa1',
    storageBucket: 'eddy-c0aa1.firebasestorage.app',
    iosBundleId: 'com.example.appTienganh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnLtyZQg3mF9YbH0dFqQvvruFVx_nnSz4',
    appId: '1:106014869880:web:faf933faab01ac9c5d208d',
    messagingSenderId: '106014869880',
    projectId: 'eddy-c0aa1',
    authDomain: 'eddy-c0aa1.firebaseapp.com',
    storageBucket: 'eddy-c0aa1.firebasestorage.app',
    measurementId: 'G-2X3KP1HZPN',
  );

}